### PR TITLE
Platform guard patch for predefined specs

### PR DESCRIPTION
**Pull request by elia**
@iliabylich please review 🙏, maybe there's a cleaner way with parser

### CODE REVIEW

**Comment by iliabylich** [comment]
Probably it makes sense to exclude all `it {}` calls when the block contains an x-string AND the path includes `spec/ruby`. This way we could protect ourselves from random x-strings in rubyspec suite that produce invalid JS on our side. What do you think?

We could do that using a stateful AST visitor

**Comment by iliabylich** [comment]
Generally speaking any x-string in rubyspec suite is dangerous for us

**Comment by elia** [comment]
@iliabylich I'll try something among those lines, I was worried about performance (of CI runs), but it makes sense anyway. 

@Mogztter let's go with this for now and I'll open an issue for the full-solution proposed by @iliabylich we we both unblock the original PR and don't loose track of the better solution 👍 

_Long term would be cool to have a magic-comment/compiler-option to allow that, similar to how `frozen_string_literal` works._

**Comment by ggrossetie** [comment]
@elia Let's go! Thanks for the fix :+1:

**Pull request merged**
